# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rc.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'rc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08rc.proto\"?\n\x07\x41uthReq\x12\x0c\n\x04gwid\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\x12\x17\n\x0fkeepalive_intvl\x18\x03 \x01(\x05\"5\n\x08\x41uthResp\x12\x0c\n\x04gwid\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\x05\"\x1a\n\x0bRestCtrlReq\x12\x0b\n\x03req\x18\x01 \x01(\x0c\"\x1c\n\x0cRestCtrlResp\x12\x0c\n\x04resp\x18\x01 \x01(\x0c\"8\n\nDisconnReq\x12\x0c\n\x04gwid\x18\x01 \x01(\t\x12\x12\n\x05token\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_token\"\x1a\n\nSessionEnd\x12\x0c\n\x04gwid\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHREQ']._serialized_start=12
  _globals['_AUTHREQ']._serialized_end=75
  _globals['_AUTHRESP']._serialized_start=77
  _globals['_AUTHRESP']._serialized_end=130
  _globals['_RESTCTRLREQ']._serialized_start=132
  _globals['_RESTCTRLREQ']._serialized_end=158
  _globals['_RESTCTRLRESP']._serialized_start=160
  _globals['_RESTCTRLRESP']._serialized_end=188
  _globals['_DISCONNREQ']._serialized_start=190
  _globals['_DISCONNREQ']._serialized_end=246
  _globals['_SESSIONEND']._serialized_start=248
  _globals['_SESSIONEND']._serialized_end=274
# @@protoc_insertion_point(module_scope)
